"""
Curated GIF library - verified Tenor CDN URLs.
Used as a fallback when the live Tenor API is unreachable, so the GIF
experience never breaks. Each entry carries search tags for offline filtering.
"""

CURATED_GIFS = [
    {
        "id": "5126644939264248578",
        "title": "a man is sitting at a table with a tray of food on it",
        "url": "https://media.tenor.com/RyWAaP5mSwIAAAAC/table-mess-lmao.gif",
        "preview": "https://media.tenor.com/RyWAaP5mSwIAAAAM/table-mess-lmao.gif",
        "width": 373,
        "height": 498,
        "tags": "laughing a man is sitting at a table with a tray of food on it",
    },
    {
        "id": "3125054571937073341",
        "title": "a woman is laughing while wearing a floral shirt and smiling .",
        "url": "https://media.tenor.com/K15sk3AFCL0AAAAC/laughing-laughing-hysterically.gif",
        "preview": "https://media.tenor.com/K15sk3AFCL0AAAAM/laughing-laughing-hysterically.gif",
        "width": 498,
        "height": 390,
        "tags": "laughing a woman is laughing while wearing a floral shirt and smiling .",
    },
    {
        "id": "7322497895326594045",
        "title": "a baby is making a funny face with his eyes closed and his mouth open .",
        "url": "https://media.tenor.com/ZZ69Ch98s_0AAAAC/baby-stray-kids.gif",
        "preview": "https://media.tenor.com/ZZ69Ch98s_0AAAAM/baby-stray-kids.gif",
        "width": 92,
        "height": 130,
        "tags": "laughing a baby is making a funny face with his eyes closed and his mouth open .",
    },
    {
        "id": "459538342932149262",
        "title": "a man in a blue shirt and tie is saying oh my god wow .",
        "url": "https://media.tenor.com/BmCbsCskdA4AAAAC/omg-oh-my-god.gif",
        "preview": "https://media.tenor.com/BmCbsCskdA4AAAAM/omg-oh-my-god.gif",
        "width": 332,
        "height": 332,
        "tags": "omg wow a man in a blue shirt and tie is saying oh my god wow .",
    },
    {
        "id": "2074021595659835685",
        "title": "a man in a striped shirt and tie is making a funny face .",
        "url": "https://media.tenor.com/HMhnpxHLGSUAAAAC/rude.gif",
        "preview": "https://media.tenor.com/HMhnpxHLGSUAAAAM/rude.gif",
        "width": 220,
        "height": 188,
        "tags": "omg wow a man in a striped shirt and tie is making a funny face .",
    },
    {
        "id": "13105127215766961484",
        "title": "a cartoon cat wearing sunglasses has the word omg on its chest",
        "url": "https://media.tenor.com/td7DxNAX_UwAAAAC/mochi-mochimons.gif",
        "preview": "https://media.tenor.com/td7DxNAX_UwAAAAM/mochi-mochimons.gif",
        "width": 498,
        "height": 498,
        "tags": "omg wow a cartoon cat wearing sunglasses has the word omg on its chest",
    },
    {
        "id": "12359774109852515591",
        "title": "a glass heart with red lines and bubbles on it",
        "url": "https://media.tenor.com/q4a9EWnUPQcAAAAC/glass-red-heart-fire.gif",
        "preview": "https://media.tenor.com/q4a9EWnUPQcAAAAM/glass-red-heart-fire.gif",
        "width": 400,
        "height": 400,
        "tags": "love heart a glass heart with red lines and bubbles on it",
    },
    {
        "id": "11313099455746202167",
        "title": "a pair of red hands make a heart shape",
        "url": "https://media.tenor.com/nQA0BABq2jcAAAAC/i-love-you-gif-by-good-vibes-club-love.gif",
        "preview": "https://media.tenor.com/nQA0BABq2jcAAAAM/i-love-you-gif-by-good-vibes-club-love.gif",
        "width": 498,
        "height": 498,
        "tags": "love heart a pair of red hands make a heart shape",
    },
    {
        "id": "2491876313249185328",
        "title": "a monkey is making a heart shape with its hands and the words `` i love you '' .",
        "url": "https://media.tenor.com/IpTsTettfjAAAAAC/love-i-love-you.gif",
        "preview": "https://media.tenor.com/IpTsTettfjAAAAAM/love-i-love-you.gif",
        "width": 320,
        "height": 480,
        "tags": "love heart a monkey is making a heart shape with its hands and the words `` i love you '' .",
    },
    {
        "id": "1191280804497482638",
        "title": "a man with a beard is wearing an adidas hat and says the fuse has been lit",
        "url": "https://media.tenor.com/EIhHlHvQY44AAAAC/the-fuse-has-been-lit-godku.gif",
        "preview": "https://media.tenor.com/EIhHlHvQY44AAAAM/the-fuse-has-been-lit-godku.gif",
        "width": 498,
        "height": 278,
        "tags": "fire lit a man with a beard is wearing an adidas hat and says the fuse has been lit",
    },
    {
        "id": "14024222989966968015",
        "title": "elmo is surrounded by flames and the words lit content are above him",
        "url": "https://media.tenor.com/wqAMgX_ZBM8AAAAC/lit-content.gif",
        "preview": "https://media.tenor.com/wqAMgX_ZBM8AAAAM/lit-content.gif",
        "width": 498,
        "height": 339,
        "tags": "fire lit elmo is surrounded by flames and the words lit content are above him",
    },
    {
        "id": "1737563225167997208",
        "title": "a cartoon of a man roasting marshmallows in front of a fire with the words that ",
        "url": "https://media.tenor.com/GB0QjBrrqRgAAAAC/egonauts-egonaut.gif",
        "preview": "https://media.tenor.com/GB0QjBrrqRgAAAAM/egonauts-egonaut.gif",
        "width": 498,
        "height": 498,
        "tags": "fire lit a cartoon of a man roasting marshmallows in front of a fire with the words that ",
    },
    {
        "id": "8329003363132079934",
        "title": "a group of people are jumping in the air in a room while a man holds a woman 's ",
        "url": "https://media.tenor.com/c5aQbgiFfz4AAAAC/friday-happydance.gif",
        "preview": "https://media.tenor.com/c5aQbgiFfz4AAAAM/friday-happydance.gif",
        "width": 413,
        "height": 498,
        "tags": "dancing party a group of people are jumping in the air in a room while a man holds a woman 's ",
    },
    {
        "id": "6044054588703599226",
        "title": "a group of elderly people are dancing in a park with the words party like it 's ",
        "url": "https://media.tenor.com/U-DLoCq_anoAAAAC/ace-ventura-pet-detective-ace-ventura.gif",
        "preview": "https://media.tenor.com/U-DLoCq_anoAAAAM/ace-ventura-pet-detective-ace-ventura.gif",
        "width": 498,
        "height": 343,
        "tags": "dancing party a group of elderly people are dancing in a park with the words party like it 's ",
    },
    {
        "id": "8297890199197514653",
        "title": "a man in a tutu is jumping in the air while a group of people watch .",
        "url": "https://media.tenor.com/cygHLAxc-50AAAAC/happy-dance.gif",
        "preview": "https://media.tenor.com/cygHLAxc-50AAAAM/happy-dance.gif",
        "width": 365,
        "height": 498,
        "tags": "dancing party a man in a tutu is jumping in the air while a group of people watch .",
    },
    {
        "id": "7893319554662649172",
        "title": "a close up of a woman 's face with a tear on her eye .",
        "url": "https://media.tenor.com/bYq0UHpPzVQAAAAC/reaction-meme-stan-twitter.gif",
        "preview": "https://media.tenor.com/bYq0UHpPzVQAAAAM/reaction-meme-stan-twitter.gif",
        "width": 415,
        "height": 498,
        "tags": "crying sad a close up of a woman 's face with a tear on her eye .",
    },
    {
        "id": "11502171953496160622",
        "title": "a man with a beard covering his mouth with his hand",
        "url": "https://media.tenor.com/n5_sc1mZeW4AAAAC/sad-crying.gif",
        "preview": "https://media.tenor.com/n5_sc1mZeW4AAAAM/sad-crying.gif",
        "width": 498,
        "height": 498,
        "tags": "crying sad a man with a beard covering his mouth with his hand",
    },
    {
        "id": "17237467286723257114",
        "title": "a cartoon teddy bear is crying and covering his face with his hand .",
        "url": "https://media.tenor.com/7zfJK1SOYxoAAAAC/milk-and-mocha.gif",
        "preview": "https://media.tenor.com/7zfJK1SOYxoAAAAM/milk-and-mocha.gif",
        "width": 498,
        "height": 452,
        "tags": "crying sad a cartoon teddy bear is crying and covering his face with his hand .",
    },
    {
        "id": "4336971722068174871",
        "title": "a man with a mustache is sitting in a chair with his eyes closed and says yes ag",
        "url": "https://media.tenor.com/PDAEzY7JqBcAAAAC/agree.gif",
        "preview": "https://media.tenor.com/PDAEzY7JqBcAAAAM/agree.gif",
        "width": 498,
        "height": 349,
        "tags": "yes agree a man with a mustache is sitting in a chair with his eyes closed and says yes ag",
    },
    {
        "id": "15045655476187652227",
        "title": "a man in an american flag costume is laying on the ground with the words i agree",
        "url": "https://media.tenor.com/0Mzn8LcTYIMAAAAC/benjammins-this-is-true.gif",
        "preview": "https://media.tenor.com/0Mzn8LcTYIMAAAAM/benjammins-this-is-true.gif",
        "width": 498,
        "height": 498,
        "tags": "yes agree a man in an american flag costume is laying on the ground with the words i agree",
    },
    {
        "id": "6573991623393037179",
        "title": "a man wearing sunglasses and a suit is holding a card and says ' 100 % agree '",
        "url": "https://media.tenor.com/WzuCjQy8S3sAAAAC/yes-subway-takes.gif",
        "preview": "https://media.tenor.com/WzuCjQy8S3sAAAAM/yes-subway-takes.gif",
        "width": 332,
        "height": 498,
        "tags": "yes agree a man wearing sunglasses and a suit is holding a card and says ' 100 % agree '",
    },
    {
        "id": "6845585744785268799",
        "title": "a man in a suit and tie is saying whataat",
        "url": "https://media.tenor.com/XwBn9yVnYD8AAAAC/kto-kounotori.gif",
        "preview": "https://media.tenor.com/XwBn9yVnYD8AAAAM/kto-kounotori.gif",
        "width": 498,
        "height": 498,
        "tags": "no way a man in a suit and tie is saying whataat",
    },
    {
        "id": "5805292699748617405",
        "title": "a man wearing sunglasses says ' absolutely not ' no way",
        "url": "https://media.tenor.com/UJCK8-GvTL0AAAAC/schitt%27s-creek-david-schitts-creek.gif",
        "preview": "https://media.tenor.com/UJCK8-GvTL0AAAAM/schitt%27s-creek-david-schitts-creek.gif",
        "width": 498,
        "height": 374,
        "tags": "no way a man wearing sunglasses says ' absolutely not ' no way",
    },
    {
        "id": "2266397159235591106",
        "title": "a cat with its mouth open and the words `` no way '' written on it .",
        "url": "https://media.tenor.com/H3PcNVwxG8IAAAAC/cat-cat-memes.gif",
        "preview": "https://media.tenor.com/H3PcNVwxG8IAAAAM/cat-cat-memes.gif",
        "width": 220,
        "height": 172,
        "tags": "no way a cat with its mouth open and the words `` no way '' written on it .",
    },
    {
        "id": "3692839162282326292",
        "title": "a naked cat with a beard and a necklace around its neck",
        "url": "https://media.tenor.com/Mz-ZpxB9ORQAAAAC/cat-dance.gif",
        "preview": "https://media.tenor.com/Mz-ZpxB9ORQAAAAM/cat-dance.gif",
        "width": 324,
        "height": 498,
        "tags": "cat funny a naked cat with a beard and a necklace around its neck",
    },
    {
        "id": "693344121160663519",
        "title": "a cat sits in front of a computer screen that says aaa on it",
        "url": "https://media.tenor.com/CZ9AzgDjAd8AAAAC/aa-aaa.gif",
        "preview": "https://media.tenor.com/CZ9AzgDjAd8AAAAM/aa-aaa.gif",
        "width": 374,
        "height": 498,
        "tags": "cat funny a cat sits in front of a computer screen that says aaa on it",
    },
    {
        "id": "10050334677379985646",
        "title": "two cats wearing scarves and sweaters are sitting next to each other looking at ",
        "url": "https://media.tenor.com/i3n2I98GMO4AAAAC/laughing-cats.gif",
        "preview": "https://media.tenor.com/i3n2I98GMO4AAAAM/laughing-cats.gif",
        "width": 480,
        "height": 480,
        "tags": "cat funny two cats wearing scarves and sweaters are sitting next to each other looking at ",
    },
    {
        "id": "2474655349647830482",
        "title": "a small brown and white puppy is sitting on a tiled floor looking at the camera ",
        "url": "https://media.tenor.com/Ile97eFHbdIAAAAC/doggy-cute.gif",
        "preview": "https://media.tenor.com/Ile97eFHbdIAAAAM/doggy-cute.gif",
        "width": 498,
        "height": 498,
        "tags": "dog cute a small brown and white puppy is sitting on a tiled floor looking at the camera ",
    },
    {
        "id": "14557949666215426227",
        "title": "a black dog is looking up at the camera with its tongue out",
        "url": "https://media.tenor.com/ygg6FxDJeLMAAAAC/sealdog-black-dog-wagging-tail.gif",
        "preview": "https://media.tenor.com/ygg6FxDJeLMAAAAM/sealdog-black-dog-wagging-tail.gif",
        "width": 281,
        "height": 498,
        "tags": "dog cute a black dog is looking up at the camera with its tongue out",
    },
    {
        "id": "11162655627106724945",
        "title": "a husky puppy is running on a brick sidewalk .",
        "url": "https://media.tenor.com/mum4Jou2LFEAAAAC/dog-cute.gif",
        "preview": "https://media.tenor.com/mum4Jou2LFEAAAAM/dog-cute.gif",
        "width": 498,
        "height": 498,
        "tags": "dog cute a husky puppy is running on a brick sidewalk .",
    },
    {
        "id": "4701085271605465312",
        "title": "a man is eating a plate of food from a plate .",
        "url": "https://media.tenor.com/QT2cJajdUOAAAAAC/martin-lawrence.gif",
        "preview": "https://media.tenor.com/QT2cJajdUOAAAAAM/martin-lawrence.gif",
        "width": 498,
        "height": 498,
        "tags": "food hungry a man is eating a plate of food from a plate .",
    },
    {
        "id": "12173863439799301633",
        "title": "a cartoon of winnie the pooh sitting at a table with a plate and spoon",
        "url": "https://media.tenor.com/qPJATHFaNgEAAAAC/winnie-the-pooh-hungry.gif",
        "preview": "https://media.tenor.com/qPJATHFaNgEAAAAM/winnie-the-pooh-hungry.gif",
        "width": 498,
        "height": 498,
        "tags": "food hungry a cartoon of winnie the pooh sitting at a table with a plate and spoon",
    },
    {
        "id": "3231678090998119807",
        "title": "a cartoon mouse in a diaper is yawning while holding a microphone and says `` i ",
        "url": "https://media.tenor.com/LNk6GgJa_X8AAAAC/food-nibbles.gif",
        "preview": "https://media.tenor.com/LNk6GgJa_X8AAAAM/food-nibbles.gif",
        "width": 498,
        "height": 493,
        "tags": "food hungry a cartoon mouse in a diaper is yawning while holding a microphone and says `` i ",
    },
    {
        "id": "15125181985284030001",
        "title": "a man wearing a jersey that says cma cl",
        "url": "https://media.tenor.com/0edw4QP9_jEAAAAC/happy-football.gif",
        "preview": "https://media.tenor.com/0edw4QP9_jEAAAAM/happy-football.gif",
        "width": 498,
        "height": 498,
        "tags": "sports goal a man wearing a jersey that says cma cl",
    },
    {
        "id": "7960088361290214945",
        "title": "a group of children are playing soccer and one of them has the number 6 on their",
        "url": "https://media.tenor.com/bnfqMLNsriEAAAAC/sports-goal.gif",
        "preview": "https://media.tenor.com/bnfqMLNsriEAAAAM/sports-goal.gif",
        "width": 483,
        "height": 498,
        "tags": "sports goal a group of children are playing soccer and one of them has the number 6 on their",
    },
    {
        "id": "10283545590448509469",
        "title": "a robot mascot is kicking a soccer ball in front of a sign that says digi 995",
        "url": "https://media.tenor.com/jrZ-Ot430h0AAAAC/usa-goal-soccer-goal.gif",
        "preview": "https://media.tenor.com/jrZ-Ot430h0AAAAM/usa-goal-soccer-goal.gif",
        "width": 450,
        "height": 450,
        "tags": "sports goal a robot mascot is kicking a soccer ball in front of a sign that says digi 995",
    },
    {
        "id": "6765568806733652206",
        "title": "a man in a black shirt with the letter y on it is jumping in the air",
        "url": "https://media.tenor.com/XeQg-_TSoO4AAAAC/riley-epic-win-epic.gif",
        "preview": "https://media.tenor.com/XeQg-_TSoO4AAAAM/riley-epic-win-epic.gif",
        "width": 480,
        "height": 270,
        "tags": "gaming win a man in a black shirt with the letter y on it is jumping in the air",
    },
    {
        "id": "12984788482852604367",
        "title": "a cartoon of a penguin wearing boxing gloves and a helmet with the word victory ",
        "url": "https://media.tenor.com/tDM8VCwDSc8AAAAC/game-party.gif",
        "preview": "https://media.tenor.com/tDM8VCwDSc8AAAAM/game-party.gif",
        "width": 498,
        "height": 498,
        "tags": "gaming win a cartoon of a penguin wearing boxing gloves and a helmet with the word victory ",
    },
    {
        "id": "15290274946109826056",
        "title": "a robot wearing a digi 995 hoodie holding a game controller",
        "url": "https://media.tenor.com/1DH4DVjuZAgAAAAC/digi-995-digi995.gif",
        "preview": "https://media.tenor.com/1DH4DVjuZAgAAAAM/digi-995-digi995.gif",
        "width": 450,
        "height": 450,
        "tags": "gaming win a robot wearing a digi 995 hoodie holding a game controller",
    },
    {
        "id": "3826864211589235688",
        "title": "a crowd of people are sitting in a theatre applauding .",
        "url": "https://media.tenor.com/NRvAuY9ug-gAAAAC/applause-clapping.gif",
        "preview": "https://media.tenor.com/NRvAuY9ug-gAAAAM/applause-clapping.gif",
        "width": 498,
        "height": 278,
        "tags": "clapping applause a crowd of people are sitting in a theatre applauding .",
    },
    {
        "id": "3068627328710602796",
        "title": "a group of people are applauding in a theatre .",
        "url": "https://media.tenor.com/KpX0TBPZ8CwAAAAC/congrats-noice.gif",
        "preview": "https://media.tenor.com/KpX0TBPZ8CwAAAAM/congrats-noice.gif",
        "width": 498,
        "height": 277,
        "tags": "clapping applause a group of people are applauding in a theatre .",
    },
    {
        "id": "10504381322816577782",
        "title": "a man and a woman are clapping their hands in a crowd .",
        "url": "https://media.tenor.com/kccPKJO64PYAAAAC/america-ferrera-clapping.gif",
        "preview": "https://media.tenor.com/kccPKJO64PYAAAAM/america-ferrera-clapping.gif",
        "width": 498,
        "height": 280,
        "tags": "clapping applause a man and a woman are clapping their hands in a crowd .",
    },
    {
        "id": "14740792841730535821",
        "title": "a cartoon of donald duck sleeping in a bed with the words good night written bel",
        "url": "https://media.tenor.com/zJHQ_U74MY0AAAAC/night-night-good-night.gif",
        "preview": "https://media.tenor.com/zJHQ_U74MY0AAAAM/night-night-good-night.gif",
        "width": 416,
        "height": 498,
        "tags": "good night a cartoon of donald duck sleeping in a bed with the words good night written bel",
    },
    {
        "id": "14932755181485165841",
        "title": "a picture of a kitten with its mouth open and the words good night",
        "url": "https://media.tenor.com/zzvNuG5MDREAAAAC/good-night-goodnight.gif",
        "preview": "https://media.tenor.com/zzvNuG5MDREAAAAM/good-night-goodnight.gif",
        "width": 208,
        "height": 208,
        "tags": "good night a picture of a kitten with its mouth open and the words good night",
    },
    {
        "id": "11461502105078477462",
        "title": "a cartoon of snoopy standing next to a crescent moon with the words ' good night",
        "url": "https://media.tenor.com/nw9vcF2YMpYAAAAC/goodnight-goodnightgif.gif",
        "preview": "https://media.tenor.com/nw9vcF2YMpYAAAAM/goodnight-goodnightgif.gif",
        "width": 412,
        "height": 498,
        "tags": "good night a cartoon of snoopy standing next to a crescent moon with the words ' good night",
    },
    {
        "id": "3871958007851095733",
        "title": "a little girl wearing a vest and tie is cheering with her fist in the air",
        "url": "https://media.tenor.com/Nbv1SysxlrUAAAAC/heavenly-joy-jerkins-i-am-so-excited.gif",
        "preview": "https://media.tenor.com/Nbv1SysxlrUAAAAM/heavenly-joy-jerkins-i-am-so-excited.gif",
        "width": 498,
        "height": 348,
        "tags": "happy excited a little girl wearing a vest and tie is cheering with her fist in the air",
    },
    {
        "id": "18194358583283106251",
        "title": "a man in a blue shirt and tie is laughing with his hands in the air",
        "url": "https://media.tenor.com/_H9Yu9CrQcsAAAAC/excited-anticipation.gif",
        "preview": "https://media.tenor.com/_H9Yu9CrQcsAAAAM/excited-anticipation.gif",
        "width": 498,
        "height": 385,
        "tags": "happy excited a man in a blue shirt and tie is laughing with his hands in the air",
    },
    {
        "id": "4789461822006618335",
        "title": "a baby without a shirt is playing in the water and smiling",
        "url": "https://media.tenor.com/QneWJsX_6N8AAAAC/whaaaa.gif",
        "preview": "https://media.tenor.com/QneWJsX_6N8AAAAM/whaaaa.gif",
        "width": 480,
        "height": 240,
        "tags": "happy excited a baby without a shirt is playing in the water and smiling",
    },
    {
        "id": "10462967706484653137",
        "title": "a screen that says choose on it in green letters",
        "url": "https://media.tenor.com/kTPtsaFmvFEAAAAC/evening-good-evening.gif",
        "preview": "https://media.tenor.com/kTPtsaFmvFEAAAAM/evening-good-evening.gif",
        "width": 498,
        "height": 281,
        "tags": "vibes mood a screen that says choose on it in green letters",
    },
    {
        "id": "6732828319116522904",
        "title": "a cartoon girl with a headband that says vibe on it",
        "url": "https://media.tenor.com/XW_PryahdZgAAAAC/vibe-good-vibes.gif",
        "preview": "https://media.tenor.com/XW_PryahdZgAAAAM/vibe-good-vibes.gif",
        "width": 399,
        "height": 498,
        "tags": "vibes mood a cartoon girl with a headband that says vibe on it",
    },
    {
        "id": "17768036477665539417",
        "title": "a poster that says ' good vibes only ' on it",
        "url": "https://media.tenor.com/9pS_CY9v9VkAAAAC/good-vibes-only-quote.gif",
        "preview": "https://media.tenor.com/9pS_CY9v9VkAAAAM/good-vibes-only-quote.gif",
        "width": 280,
        "height": 498,
        "tags": "vibes mood a poster that says ' good vibes only ' on it",
    },
]
