from app.models import db, Post, environment, SCHEMA
from sqlalchemy.sql import text
from datetime import datetime, timedelta
import json
import random

SH = 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-{}.mp3'
PX = 'https://videos.pexels.com/video-files/{}'
TN = 'https://media.tenor.com/{}'
WM = 'https://upload.wikimedia.org/wikipedia/commons/transcoded/{}'


def seed_posts():
    """
    Video-first seed data: vertical lifestyle clips (Pexels), open-source
    films with real audio (Wikimedia/Blender), looping meme videos (Tenor),
    GIF posts and classic ABLN photo posts. All remote URLs verified.
    """
    posts_data = [
        # ---- Vertical lifestyle videos (Pexels) ----
        {"user_id": 2, "media_type": "video",
         "video_url": PX.format('4434286/4434286-hd_1080_1920_30fps.mp4'),
         "body": "POV: the night is just getting started 🌃 #dance #nightout #vibes #fyp",
         "sound_name": "Neon Nights", "sound_url": SH.format(2),
         "views": 248312, "shares": 842},
        {"user_id": 6, "media_type": "video",
         "video_url": PX.format('8859849/8859849-hd_1080_1920_25fps.mp4'),
         "body": "main character energy only ✨ #aesthetic #mood #fyp",
         "sound_name": "Glow Up", "sound_url": SH.format(4),
         "views": 175204, "shares": 511},
        {"user_id": 3, "media_type": "video",
         "video_url": PX.format('4625747/4625747-hd_1080_1920_24fps.mp4'),
         "body": "city lights hit different at 2am 🌌 #nightdrive #citylights #travel",
         "sound_name": "Midnight Drive", "sound_url": SH.format(3),
         "views": 132877, "shares": 367},
        {"user_id": 7, "media_type": "video",
         "video_url": PX.format('5992585/5992585-hd_1080_1920_25fps.mp4'),
         "body": "no days off 💪 morning after the party still counts #fitness #gym #grind",
         "sound_name": "2AM Energy", "sound_url": SH.format(6),
         "views": 98321, "shares": 203},
        {"user_id": 5, "media_type": "video",
         "video_url": PX.format('4678261/4678261-hd_1080_1920_25fps.mp4'),
         "body": "about last night… no caption needed 🤫 #aboutlastnight #abln #nightout",
         "sound_name": "About Last Night (Anthem)", "sound_url": SH.format(1),
         "views": 312940, "shares": 1204},
        {"user_id": 9, "media_type": "video",
         "video_url": PX.format('5057524/5057524-hd_1080_1920_25fps.mp4'),
         "body": "cozy reset after the weekend 🌿 self care sunday #cozy #mood #reset",
         "sound_name": "Afterglow", "sound_url": SH.format(12),
         "views": 67233, "shares": 98},
        {"user_id": 2, "media_type": "video",
         "video_url": PX.format('8045175/8045175-hd_1080_1920_25fps.mp4'),
         "body": "learning this choreo took 47 tries 😅 worth it #dance #choreo #practice",
         "sound_name": "Dance Floor Gravity", "sound_url": SH.format(11),
         "views": 154002, "shares": 488},
        {"user_id": 10, "media_type": "video",
         "video_url": PX.format('6963395/6963395-hd_1080_1920_25fps.mp4'),
         "body": "midnight snack run = elite 🍜 rate the order #food #foodie #midnightsnack",
         "sound_name": "Last Call", "sound_url": SH.format(5),
         "views": 88450, "shares": 176},
        {"user_id": 6, "media_type": "video",
         "video_url": PX.format('7515918/7515918-hd_1080_1920_30fps.mp4'),
         "body": "golden hour never misses 📸 #goldenhour #aesthetic #sunset #travel",
         "sound_name": "Golden Hour Groove", "sound_url": SH.format(13),
         "views": 121980, "shares": 320},
        {"user_id": 3, "media_type": "video",
         "video_url": PX.format('6010489/6010489-hd_1080_1920_25fps.mp4'),
         "body": "this view was 100% worth the hike 🌅 #adventure #sunrise #travel #nature",
         "sound_name": "Rooftop Sunrise", "sound_url": SH.format(7),
         "views": 76112, "shares": 142},

        # ---- Landscape cinematic (Pexels) ----
        {"user_id": 3, "media_type": "video",
         "video_url": PX.format('3195394/3195394-hd_1920_1080_25fps.mp4'),
         "body": "drone over paradise 🏝️ saving this for the group trip #travel #beach #drone",
         "sound_name": "Weekend Forecast", "sound_url": SH.format(15),
         "views": 201733, "shares": 654},
        {"user_id": 5, "media_type": "video",
         "video_url": PX.format('1409899/1409899-hd_1920_1080_25fps.mp4'),
         "body": "the finale from last night was UNREAL 🎆 #fireworks #aboutlastnight #festival",
         "sound_name": "Confetti Rain", "sound_url": SH.format(9),
         "views": 187420, "shares": 590},
        {"user_id": 1, "media_type": "video",
         "video_url": PX.format('3209828/3209828-hd_1920_1080_25fps.mp4'),
         "body": "ocean therapy. that's the post 🌊 #beach #waves #calm #nature",
         "sound_name": "City Lights Lullaby", "sound_url": SH.format(14),
         "views": 54219, "shares": 87},

        # ---- Open-source films w/ real audio (Wikimedia / Blender Foundation) ----
        {"user_id": 11, "media_type": "video",
         "video_url": WM.format('c/c0/Big_Buck_Bunny_4K.webm/Big_Buck_Bunny_4K.webm.720p.vp9.webm'),
         "body": "movie night pick: Big Buck Bunny 🐰 a classic. sound ON #films #animation #movienight",
         "sound_name": "Original sound — luna.films", "sound_url": None,
         "views": 96234, "shares": 233},
        {"user_id": 11, "media_type": "video",
         "video_url": WM.format('f/f1/Sintel_movie_4K.webm/Sintel_movie_4K.webm.720p.vp9.webm'),
         "body": "Sintel still makes me cry every time 🐉 #films #animation #blender #emotional",
         "sound_name": "Original sound — luna.films", "sound_url": None,
         "views": 74110, "shares": 198},
        {"user_id": 11, "media_type": "video",
         "video_url": WM.format('1/10/Tears_of_Steel_in_4k_-_Official_Blender_Foundation_release.webm/Tears_of_Steel_in_4k_-_Official_Blender_Foundation_release.webm.720p.vp9.webm'),
         "body": "sci-fi short film night 🤖 Tears of Steel — effects are wild #films #scifi #shortfilm",
         "sound_name": "Original sound — luna.films", "sound_url": None,
         "views": 58772, "shares": 130},
        {"user_id": 8, "media_type": "video",
         "video_url": WM.format('8/82/Glass_Half_-_3D_animation_with_OpenGL_cartoon_rendering.webm/Glass_Half_-_3D_animation_with_OpenGL_cartoon_rendering.webm.720p.vp9.webm'),
         "body": "this short is basically every game night argument 😂 #films #comedy #animation",
         "sound_name": "Original sound — dnd_lord", "sound_url": None,
         "views": 41230, "shares": 75},

        # ---- Looping meme videos (Tenor) ----
        {"user_id": 12, "media_type": "video",
         "video_url": TN.format('QAnzKVdtaj4AAAPo/marmot-ai-dance.mp4'),
         "body": "me when the weekend finally loads 😂 #funny #dance #meme #animals",
         "sound_name": "Strobe Light Heartbeat", "sound_url": SH.format(10),
         "views": 264102, "shares": 1490},
        {"user_id": 2, "media_type": "video",
         "video_url": TN.format('Ffl1k0f2bgIAAAPo/dance-moves.mp4'),
         "body": "tutu tuesday is real and it's beautiful 🩰 #dance #funny #energy",
         "sound_name": "Encore Encore", "sound_url": SH.format(16),
         "views": 95210, "shares": 410},
        {"user_id": 6, "media_type": "video",
         "video_url": TN.format('KHIxTvsDJV8AAAPo/funny-dancing.mp4'),
         "body": "the bee costume kid won the whole night 🐝😭 #funny #comedy #iconic",
         "sound_name": "Confetti Rain", "sound_url": SH.format(9),
         "views": 188233, "shares": 977},
        {"user_id": 12, "media_type": "video",
         "video_url": TN.format('GnT6WEh2xYkAAAPo/cat-showercap-slyonicz.mp4'),
         "body": "spa night with the girls 🧖‍♀️🐱 #cat #funny #selfcare #animals",
         "sound_name": "Afterglow", "sound_url": SH.format(12),
         "views": 143901, "shares": 689},
        {"user_id": 12, "media_type": "video",
         "video_url": TN.format('lfDATg4Bhc0AAAPo/happy-cat.mp4'),
         "body": "POV: someone said 'treats' 🐱 #cat #happy #animals #wholesome",
         "sound_name": "Glow Up", "sound_url": SH.format(4),
         "views": 77450, "shares": 256},
        {"user_id": 8, "media_type": "video",
         "video_url": TN.format('XeQg-_TSoO4AAAPo/riley-epic-win-epic.mp4'),
         "body": "when the squad finally wins the ranked match 🎮 #gaming #win #clutch",
         "sound_name": "2AM Energy", "sound_url": SH.format(6),
         "views": 112380, "shares": 364},
        {"user_id": 8, "media_type": "video",
         "video_url": TN.format('tDM8VCwDSc8AAAPo/game-party.mp4'),
         "body": "game night is getting SERIOUS 🥊🐧 #gaming #gamenight #funny",
         "sound_name": "Bass in the Basement", "sound_url": SH.format(8),
         "views": 64310, "shares": 122},
        {"user_id": 10, "media_type": "video",
         "video_url": TN.format('PRd2U1dLAAUAAAPo/winnie-the-pooh-hungry.mp4'),
         "body": "me waiting for the food to arrive 🍯 #food #hungry #mood #relatable",
         "sound_name": "Last Call", "sound_url": SH.format(5),
         "views": 93120, "shares": 301},
        {"user_id": 10, "media_type": "video",
         "video_url": TN.format('skSsVIox1a8AAAPo/love-food-yum-yum.mp4'),
         "body": "rating last night's menu: 10/10 would devour again 😋 #food #foodie #yum",
         "sound_name": "Golden Hour Groove", "sound_url": SH.format(13),
         "views": 58440, "shares": 119},
        {"user_id": 4, "media_type": "video",
         "video_url": TN.format('YfGMmvy4ZxAAAAPo/rockets-basketball.mp4'),
         "body": "THE BUZZER BEATER FROM LAST NIGHT 🏀🔥 #sports #basketball #clutch #goal",
         "sound_name": "Encore Encore", "sound_url": SH.format(16),
         "views": 171204, "shares": 745},
        {"user_id": 4, "media_type": "video",
         "video_url": TN.format('VJZl5fqo9SkAAAPo/play-sports-premier-league.mp4'),
         "body": "saturday football >>> everything else ⚽ #sports #soccer #gameday",
         "sound_name": "Weekend Forecast", "sound_url": SH.format(15),
         "views": 84290, "shares": 215},
        {"user_id": 4, "media_type": "video",
         "video_url": TN.format('3K9-39_EAX0AAAPo/vincent-jackson-high-five.mp4'),
         "body": "celebrating like we won the championship (we lost) 😂 #sports #funny #team",
         "sound_name": "Confetti Rain", "sound_url": SH.format(9),
         "views": 47102, "shares": 88},
        {"user_id": 12, "media_type": "video",
         "video_url": TN.format('ygg6FxDJeLMAAAPo/sealdog-black-dog-wagging-tail.mp4'),
         "body": "he heard 'walk' once 🐶 #dog #wholesome #animals #happy",
         "sound_name": "City Lights Lullaby", "sound_url": SH.format(14),
         "views": 132450, "shares": 521},
        {"user_id": 12, "media_type": "video",
         "video_url": TN.format('FI7dxlR-1f4AAAPo/golden-retriever-rollercoaster.mp4'),
         "body": "took the dog to the theme park. no regrets 🎢🐕 #dog #funny #adventure #animals",
         "sound_name": "Strobe Light Heartbeat", "sound_url": SH.format(10),
         "views": 228190, "shares": 1102},

        # ---- GIF posts (ABLN classics) ----
        {"user_id": 6, "media_type": "gif",
         "image_url": "/images/bestiedance.gif",
         "body": "me and my bestie when our song comes on 💃💃 #gif #dance #bestie #mood",
         "sound_name": "Neon Nights", "sound_url": SH.format(2),
         "views": 99340, "shares": 451},
        {"user_id": 5, "media_type": "gif",
         "image_url": "/images/hungover-britney.gif",
         "body": "the morning after the night before… we've all been there 😵‍💫 #gif #aboutlastnight #relatable",
         "sound_name": "Sunrise Cleanup Crew", "sound_url": SH.format(17),
         "views": 87210, "shares": 376},
        {"user_id": 1, "media_type": "gif",
         "image_url": "/images/drunkdance.gif",
         "body": "my one dance move and I'm sticking with it 🕺 #gif #funny #dance #aboutlastnight",
         "sound_name": "About Last Night (Anthem)", "sound_url": SH.format(1),
         "views": 64580, "shares": 198},
        {"user_id": 7, "media_type": "gif",
         "image_url": "/images/cuttingup.gif",
         "body": "TONIGHT THE MUSIC SINGS SOOO LOUD 😎🪩 #gif #party #nightout",
         "sound_name": "Bass in the Basement", "sound_url": SH.format(8),
         "views": 51230, "shares": 134},

        # ---- Classic ABLN photo posts ----
        {"user_id": 3, "media_type": "image",
         "image_url": "/images/whotookthis.jpg",
         "body": "who took this pic 😭 ??? BROO i was GONE! 💀📸 #aboutlastnight #funny",
         "sound_name": None, "sound_url": None,
         "views": 43210, "shares": 67},
        {"user_id": 2, "media_type": "image",
         "image_url": "/images/dyehairgirl.jpg",
         "body": "just dyed my hair for the party downtown tonight, what ya think? 🌈✨ #glowup #aesthetic",
         "sound_name": None, "sound_url": None,
         "views": 38450, "shares": 51},
        {"user_id": 4, "media_type": "image",
         "image_url": "/images/lastnightmovie.jpg",
         "body": "yooo last night was a movie 🍾🪩 #aboutlastnight #party",
         "sound_name": None, "sound_url": None,
         "views": 29840, "shares": 44},
        {"user_id": 6, "media_type": "image",
         "image_url": "/images/rooftop.jpg",
         "body": "pulling up to the rooftop in 10 😎 #nightout #cityvibes",
         "sound_name": None, "sound_url": None,
         "views": 22103, "shares": 31},
        {"user_id": 9, "media_type": "image",
         "image_url": "/images/cat1.jpg",
         "body": "I was finally let into my OWN HOUSE !! 😭 #cat #funny",
         "sound_name": None, "sound_url": None,
         "views": 33920, "shares": 58},
        {"user_id": 1, "media_type": "image",
         "image_url": "/images/feltcute.jpg",
         "body": "heyyy IM NEW HERE!! 👀👋 #newhere #fyp",
         "sound_name": None, "sound_url": None,
         "views": 18230, "shares": 12},

        # ---- Multi-image carousel post (swipeable photo dump) ----
        {"user_id": 5, "media_type": "carousel",
         "image_url": "/images/rooftop.jpg",
         "images": ["/images/rooftop.jpg", "/images/lastnightmovie.jpg",
                    "/images/whotookthis.jpg", "/images/feltcute.jpg"],
         "body": "swipe through last night ➡️📸 the photo dump you didn't ask for #photodump #aboutlastnight #carousel",
         "sound_name": "About Last Night (Anthem)", "sound_url": SH.format(1),
         "views": 51420, "shares": 173},
    ]

    random.seed(99)
    now = datetime.utcnow()
    for p in posts_data:
        created = now - timedelta(days=random.randint(0, 42),
                                  hours=random.randint(0, 23),
                                  minutes=random.randint(0, 59))
        post = Post(
            user_id=p["user_id"],
            body=p["body"],
            image_url=p.get("image_url"),
            images=json.dumps(p["images"]) if p.get("images") else None,
            video_url=p.get("video_url"),
            media_type=p["media_type"],
            sound_name=p.get("sound_name"),
            sound_url=p.get("sound_url"),
            views=p.get("views", 0),
            shares=p.get("shares", 0),
            created_at=created,
            updated_at=created,
        )
        db.session.add(post)

    db.session.commit()


def undo_posts():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.posts RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM posts"))

    db.session.commit()
