"""add_updated_at_to_notifications

Revision ID: a662843816ef
Revises: 63fbb07dd2f0
Create Date: 2025-08-13 21:50:16.478259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a662843816ef'
down_revision = '63fbb07dd2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('message', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(length=255), nullable=True))
        
        # Add named foreign key constraints
        batch_op.create_foreign_key(
            'fk_notifications_post_id',
            'posts', 
            ['post_id'], 
            ['id']
        )
        batch_op.create_foreign_key(
            'fk_notifications_comment_id',
            'comments', 
            ['comment_id'], 
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        # Drop constraints by name
        batch_op.drop_constraint('fk_notifications_post_id', type_='foreignkey')
        batch_op.drop_constraint('fk_notifications_comment_id', type_='foreignkey')
        batch_op.drop_column('link')
        batch_op.drop_column('message')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###