"""Add pending column to friends table

Revision ID: 608c7adc8ab4
Revises: bb21ebafee02
Create Date: 2025-08-06 00:54:58.800295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608c7adc8ab4'
down_revision = 'bb21ebafee02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending', sa.Boolean(), server_default='true', nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'BLOCKED', name='friendstatus'),
               existing_nullable=False)
        batch_op.create_unique_constraint('unique_friendship', ['requester_id', 'receiver_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_constraint('unique_friendship', type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'BLOCKED', name='friendstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('pending')

    # ### end Alembic commands ###
